<DragButton>
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_timeout: 10000
    drag_distance: 0
    text: 'Hi'
    size_hint: (1, .5)

<MainScreen>
    splitter: split
    boxlayout: box
    
    BoxLayout:
        size: root.width, root.height
        orientation: 'horizontal'

        BoxLayout:
            id: box
            orientation: 'vertical'
            Label:
                text: 'Widgets'
                size_hint: (1, .25)
            
            DragButton:
                on_center_x: root.dragged(self)
            
            DragButton:
                on_center_x: root.dragged(self)

            DragButton:
                on_center_x: root.dragged(self)


        Splitter:
            id: split
            sizable_from: 'left'
            Label:
                text: 'Check If they are here'